### ISSUE TITLE
How did you start coding?

### ISSUE THREAD

**Issue by IonicaBizau** [egoist/ama#6]
I noticed nice stuff around, so, I'm curious to know how and when you start coding. 😁 How did you do it?

**Comment by egoist** [comment]
I started coding when I entered my college, about 4 years ago. Before then I just had some experience in using WordPress and things like that. I never wrote a line of code before college, of course not including the code I wrote on high school CS class. 

Then I went to college to learn computer science, C++ and Java are the two major subjects in my domain. These language are cool, but seldom fit my needs, I do love web and related stuffs more, due to the long time I spent playing with blogs.

I used many blog host platform, then I thought I can build my own one, and why not? 

But things changed, in 2014 blogs were not so popular as before, so I headed to build a forum software. I can understand some PHP code (thanks to wordpress 😂) and a little JS code ([as you said](http://ionicabizau.net/about), it's really easy and powerful, I learned it by reading the code of [v2ex](https://github.com/livid/v2ex), which is a forum software).

It was hard, I didn't go to websites like w3schools or buy a book about web development, my original intention was just to have fun. My only teachers are Google and StackOverflow.

And then I simply built a theme for wordpress to make it perform exactly like a forum! You can still [preview it](http://ww2.sinaimg.cn/large/622cc51agw1ea3lc1okelj211a11tagb.jpg) or see the source code [here](https://github.com/enirehtac/Qing), it's really a learner project LOL.

Honestly I bought many books about web/js/node later, but I only read a few pages of them 😂 Most of what I know are learned by reading others' code, for example, I learned about `serial-assignment` from your code 🙃

The later stories are similar, I kept making wheels. (a real forum software and a Twitter copycat). Until then, my knowledge about JS is a mess (I'm good at googling and nothing else), I started to learn it more systematically and give more focus to the basis. I can tell the time is late 2014. Months later, in early 2015 I joined the team of [pomotodo](https://pomotodo.com/), they worked remotely and it's really cool for me, I learned coffeescript and gulp when working with them.

Obviously in the recent year I'm addicted into open-source world. I never managed to be a master of code, it just looks like a kind of game for me. The experiences are important, so are the failures. Don't be afraid to die, kill every boss in the road, at least in the developer career I am immortal. I always believe that practice makes perfect.

And the best thing is, I can make a living by it, incidentally. 🤗
