### ISSUE TITLE
How do you start new projects?

### ISSUE THREAD

**Issue by IonicaBizau** [egoist/ama#7]
How do you 🚀 a new project?

**Comment by egoist** [comment]
My workflow is quite simple 😅

1. `cd ~/dev && mkdir my-project`
2. `yo esnm`  https://github.com/egoist/generator-esnm

  Rencently I started to add a toc to my repo, [example](https://github.com/egoist/bubleup), by using [markdown-toc](https://github.com/jonschlinkert/markdown-toc) and [&lt;details&gt; tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details)

3. `code .`
4. Maybe generate a simple logo for the project using [slogan](https://github.com/egoist/slogan) since I'm not so good at sketch and photoshop 😐
5. Currently I write API doc in README by hand for small projects, sometimes using jsdoc. Maybe change this habit  in the future 😅
6. Publish with [kanpai](https://github.com/egoist/kanpai)

**Comment by egoist** [comment]
Yep, but I feel it's too verbose writing a generator for yeoman/yo 😅 while using a simple json file to manage the logic seems a better option, like https://github.com/vuejs/vue-cli
